// Code generated by protoc-gen-go. DO NOT EDIT.
// source: quota_service.proto

/*
Package quotaservice is a generated protocol buffer package.

It is generated from these files:
	quota_service.proto

It has these top-level messages:
	AllowRequest
	AllowResponse
	UpdateRequest
	UpdateResponse
	InfoRequest
	InfoResponse
*/
package quotaservice

import (
	"context"
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllowResponse_Status int32

const (
	AllowResponse_OK                                 AllowResponse_Status = 0
	AllowResponse_REJECTED_TIMEOUT                   AllowResponse_Status = 1
	AllowResponse_REJECTED_NO_BUCKET                 AllowResponse_Status = 2
	AllowResponse_REJECTED_TOO_MANY_BUCKETS          AllowResponse_Status = 3
	AllowResponse_REJECTED_TOO_MANY_TOKENS_REQUESTED AllowResponse_Status = 4
	AllowResponse_REJECTED_INVALID_REQUEST           AllowResponse_Status = 5
	AllowResponse_REJECTED_SERVER_ERROR              AllowResponse_Status = 6
)

var AllowResponse_Status_name = map[int32]string{
	0: "OK",
	1: "REJECTED_TIMEOUT",
	2: "REJECTED_NO_BUCKET",
	3: "REJECTED_TOO_MANY_BUCKETS",
	4: "REJECTED_TOO_MANY_TOKENS_REQUESTED",
	5: "REJECTED_INVALID_REQUEST",
	6: "REJECTED_SERVER_ERROR",
}
var AllowResponse_Status_value = map[string]int32{
	"OK":                                 0,
	"REJECTED_TIMEOUT":                   1,
	"REJECTED_NO_BUCKET":                 2,
	"REJECTED_TOO_MANY_BUCKETS":          3,
	"REJECTED_TOO_MANY_TOKENS_REQUESTED": 4,
	"REJECTED_INVALID_REQUEST":           5,
	"REJECTED_SERVER_ERROR":              6,
}

func (x AllowResponse_Status) String() string {
	return proto.EnumName(AllowResponse_Status_name, int32(x))
}
func (AllowResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type UpdateResponse_Status int32

const (
	UpdateResponse_OK                       UpdateResponse_Status = 0
	UpdateResponse_REJECTED_TIMEOUT         UpdateResponse_Status = 1
	UpdateResponse_REJECTED_INVALID_REQUEST UpdateResponse_Status = 2
	UpdateResponse_REJECTED_SERVER_ERROR    UpdateResponse_Status = 3
)

var UpdateResponse_Status_name = map[int32]string{
	0: "OK",
	1: "REJECTED_TIMEOUT",
	2: "REJECTED_INVALID_REQUEST",
	3: "REJECTED_SERVER_ERROR",
}
var UpdateResponse_Status_value = map[string]int32{
	"OK":                       0,
	"REJECTED_TIMEOUT":         1,
	"REJECTED_INVALID_REQUEST": 2,
	"REJECTED_SERVER_ERROR":    3,
}

func (x UpdateResponse_Status) String() string {
	return proto.EnumName(UpdateResponse_Status_name, int32(x))
}
func (UpdateResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type InfoResponse_Status int32

const (
	InfoResponse_OK                       InfoResponse_Status = 0
	InfoResponse_REJECTED_TIMEOUT         InfoResponse_Status = 1
	InfoResponse_REJECTED_NO_BUCKET       InfoResponse_Status = 2
	InfoResponse_REJECTED_INVALID_REQUEST InfoResponse_Status = 3
	InfoResponse_REJECTED_SERVER_ERROR    InfoResponse_Status = 4
)

var InfoResponse_Status_name = map[int32]string{
	0: "OK",
	1: "REJECTED_TIMEOUT",
	2: "REJECTED_NO_BUCKET",
	3: "REJECTED_INVALID_REQUEST",
	4: "REJECTED_SERVER_ERROR",
}
var InfoResponse_Status_value = map[string]int32{
	"OK":                       0,
	"REJECTED_TIMEOUT":         1,
	"REJECTED_NO_BUCKET":       2,
	"REJECTED_INVALID_REQUEST": 3,
	"REJECTED_SERVER_ERROR":    4,
}

func (x InfoResponse_Status) String() string {
	return proto.EnumName(InfoResponse_Status_name, int32(x))
}
func (InfoResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type AllowRequest struct {
	Namespace  string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	BucketName string `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName" json:"bucket_name,omitempty"`
	// *
	// Number of tokens requested. Defaults to 1, cannot be 0.
	TokensRequested int64 `protobuf:"varint,3,opt,name=tokens_requested,json=tokensRequested" json:"tokens_requested,omitempty"`
	// *
	// Max wait time, in millis. Defaults to 0, which assumes no waiting.
	MaxWaitMillisOverride int64 `protobuf:"varint,4,opt,name=max_wait_millis_override,json=maxWaitMillisOverride" json:"max_wait_millis_override,omitempty"`
	// *
	// Whether to override max wait time with the above value.
	// Defaults to false, which falls back to the bucket's configured value.
	MaxWaitTimeOverride bool `protobuf:"varint,5,opt,name=max_wait_time_override,json=maxWaitTimeOverride" json:"max_wait_time_override,omitempty"`
}

func (m *AllowRequest) Reset()                    { *m = AllowRequest{} }
func (m *AllowRequest) String() string            { return proto.CompactTextString(m) }
func (*AllowRequest) ProtoMessage()               {}
func (*AllowRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllowRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *AllowRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *AllowRequest) GetTokensRequested() int64 {
	if m != nil {
		return m.TokensRequested
	}
	return 0
}

func (m *AllowRequest) GetMaxWaitMillisOverride() int64 {
	if m != nil {
		return m.MaxWaitMillisOverride
	}
	return 0
}

func (m *AllowRequest) GetMaxWaitTimeOverride() bool {
	if m != nil {
		return m.MaxWaitTimeOverride
	}
	return false
}

type AllowResponse struct {
	Status AllowResponse_Status `protobuf:"varint,1,opt,name=status,enum=quotaservice.AllowResponse_Status" json:"status,omitempty"`
	// *
	// Number of tokens granted, if status == OK
	TokensGranted int64 `protobuf:"varint,2,opt,name=tokens_granted,json=tokensGranted" json:"tokens_granted,omitempty"`
	// *
	// Wait for this many millis before proceeding, if status == OK. 0 if no waiting is required.
	WaitMillis int64 `protobuf:"varint,3,opt,name=wait_millis,json=waitMillis" json:"wait_millis,omitempty"`
}

func (m *AllowResponse) Reset()                    { *m = AllowResponse{} }
func (m *AllowResponse) String() string            { return proto.CompactTextString(m) }
func (*AllowResponse) ProtoMessage()               {}
func (*AllowResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllowResponse) GetStatus() AllowResponse_Status {
	if m != nil {
		return m.Status
	}
	return AllowResponse_OK
}

func (m *AllowResponse) GetTokensGranted() int64 {
	if m != nil {
		return m.TokensGranted
	}
	return 0
}

func (m *AllowResponse) GetWaitMillis() int64 {
	if m != nil {
		return m.WaitMillis
	}
	return 0
}

type UpdateRequest struct {
	Namespace         string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	BucketName        string `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName" json:"bucket_name,omitempty"`
	Size              int64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	FillRate          int64  `protobuf:"varint,4,opt,name=fill_rate,json=fillRate" json:"fill_rate,omitempty"`
	WaitTimeoutMillis int64  `protobuf:"varint,5,opt,name=wait_timeout_millis,json=waitTimeoutMillis" json:"wait_timeout_millis,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *UpdateRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *UpdateRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *UpdateRequest) GetFillRate() int64 {
	if m != nil {
		return m.FillRate
	}
	return 0
}

func (m *UpdateRequest) GetWaitTimeoutMillis() int64 {
	if m != nil {
		return m.WaitTimeoutMillis
	}
	return 0
}

type UpdateResponse struct {
	Status UpdateResponse_Status `protobuf:"varint,1,opt,name=status,enum=quotaservice.UpdateResponse_Status" json:"status,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateResponse) GetStatus() UpdateResponse_Status {
	if m != nil {
		return m.Status
	}
	return UpdateResponse_OK
}

type InfoRequest struct {
	Namespace  string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	BucketName string `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName" json:"bucket_name,omitempty"`
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InfoRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InfoRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type InfoResponse struct {
	Status            InfoResponse_Status `protobuf:"varint,1,opt,name=status,enum=quotaservice.InfoResponse_Status" json:"status,omitempty"`
	Size              int64               `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	FillRate          int64               `protobuf:"varint,3,opt,name=fill_rate,json=fillRate" json:"fill_rate,omitempty"`
	WaitTimeoutMillis int64               `protobuf:"varint,4,opt,name=wait_timeout_millis,json=waitTimeoutMillis" json:"wait_timeout_millis,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InfoResponse) GetStatus() InfoResponse_Status {
	if m != nil {
		return m.Status
	}
	return InfoResponse_OK
}

func (m *InfoResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InfoResponse) GetFillRate() int64 {
	if m != nil {
		return m.FillRate
	}
	return 0
}

func (m *InfoResponse) GetWaitTimeoutMillis() int64 {
	if m != nil {
		return m.WaitTimeoutMillis
	}
	return 0
}

func init() {
	proto.RegisterType((*AllowRequest)(nil), "quotaservice.AllowRequest")
	proto.RegisterType((*AllowResponse)(nil), "quotaservice.AllowResponse")
	proto.RegisterType((*UpdateRequest)(nil), "quotaservice.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "quotaservice.UpdateResponse")
	proto.RegisterType((*InfoRequest)(nil), "quotaservice.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "quotaservice.InfoResponse")
	proto.RegisterEnum("quotaservice.AllowResponse_Status", AllowResponse_Status_name, AllowResponse_Status_value)
	proto.RegisterEnum("quotaservice.UpdateResponse_Status", UpdateResponse_Status_name, UpdateResponse_Status_value)
	proto.RegisterEnum("quotaservice.InfoResponse_Status", InfoResponse_Status_name, InfoResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for QuotaService service

type QuotaServiceClient interface {
	Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type quotaServiceClient struct {
	cc *grpc.ClientConn
}

func NewQuotaServiceClient(cc *grpc.ClientConn) QuotaServiceClient {
	return &quotaServiceClient{cc}
}

func (c *quotaServiceClient) Allow(ctx context.Context, in *AllowRequest, opts ...grpc.CallOption) (*AllowResponse, error) {
	out := new(AllowResponse)
	err := grpc.Invoke(ctx, "/quotaservice.QuotaService/Allow", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotaServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/quotaservice.QuotaService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotaServiceClient) GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/quotaservice.QuotaService/GetInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for QuotaService service

type QuotaServiceServer interface {
	Allow(context.Context, *AllowRequest) (*AllowResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	GetInfo(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterQuotaServiceServer(s *grpc.Server, srv QuotaServiceServer) {
	s.RegisterService(&_QuotaService_serviceDesc, srv)
}

func _QuotaService_Allow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).Allow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotaservice.QuotaService/Allow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).Allow(ctx, req.(*AllowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotaService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotaservice.QuotaService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotaService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quotaservice.QuotaService/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).GetInfo(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QuotaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quotaservice.QuotaService",
	HandlerType: (*QuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allow",
			Handler:    _QuotaService_Allow_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _QuotaService_Update_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _QuotaService_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quota_service.proto",
}

func init() { proto.RegisterFile("quota_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4b, 0x4f, 0x13, 0x41,
	0x1c, 0xef, 0x6e, 0x1f, 0xc2, 0x9f, 0x82, 0xeb, 0x1f, 0x21, 0xe5, 0x61, 0xc4, 0x31, 0x1a, 0xbc,
	0xf4, 0x00, 0x07, 0xa3, 0x9e, 0x78, 0x4c, 0x48, 0x05, 0xba, 0x61, 0xba, 0xc5, 0x78, 0x9a, 0x0c,
	0x30, 0x98, 0x0d, 0xdd, 0x6e, 0xd9, 0x9d, 0x52, 0xe2, 0xd7, 0xf1, 0xae, 0xdf, 0xc0, 0x4f, 0xe1,
	0xd5, 0xab, 0x9f, 0xc3, 0xec, 0xec, 0xec, 0x42, 0x2b, 0x6d, 0x48, 0xe4, 0xb6, 0xf9, 0xfd, 0x1f,
	0x99, 0xdf, 0x63, 0x66, 0x61, 0xfe, 0xb2, 0x1f, 0x2a, 0xc1, 0x63, 0x19, 0x5d, 0xf9, 0xa7, 0xb2,
	0xde, 0x8b, 0x42, 0x15, 0x62, 0x55, 0x83, 0x06, 0x23, 0x7f, 0x2c, 0xa8, 0x6e, 0x75, 0x3a, 0xe1,
	0x80, 0xc9, 0xcb, 0xbe, 0x8c, 0x15, 0xae, 0xc2, 0x74, 0x57, 0x04, 0x32, 0xee, 0x89, 0x53, 0x59,
	0xb3, 0xd6, 0xac, 0xf5, 0x69, 0x76, 0x03, 0xe0, 0x73, 0x98, 0x39, 0xe9, 0x9f, 0x5e, 0x48, 0xc5,
	0x13, 0xac, 0x66, 0xeb, 0x3a, 0xa4, 0x50, 0x53, 0x04, 0x12, 0xdf, 0x80, 0xa3, 0xc2, 0x0b, 0xd9,
	0x8d, 0x79, 0x94, 0x2e, 0x94, 0x67, 0xb5, 0xe2, 0x9a, 0xb5, 0x5e, 0x64, 0x8f, 0x53, 0x9c, 0x65,
	0x30, 0xbe, 0x85, 0x5a, 0x20, 0xae, 0xf9, 0x40, 0xf8, 0x8a, 0x07, 0x7e, 0xa7, 0xe3, 0xc7, 0x3c,
	0xbc, 0x92, 0x51, 0xe4, 0x9f, 0xc9, 0x5a, 0x49, 0x8f, 0x2c, 0x04, 0xe2, 0xfa, 0x93, 0xf0, 0xd5,
	0xa1, 0xae, 0xba, 0xa6, 0x88, 0x9b, 0xb0, 0x98, 0x0f, 0x2a, 0x3f, 0x90, 0x37, 0x63, 0xe5, 0x35,
	0x6b, 0x7d, 0x8a, 0xcd, 0x9b, 0x31, 0xcf, 0x0f, 0x64, 0x36, 0x44, 0x7e, 0xd9, 0x30, 0x6b, 0x88,
	0xc6, 0xbd, 0xb0, 0x1b, 0x4b, 0x7c, 0x0f, 0x95, 0x58, 0x09, 0xd5, 0x8f, 0x35, 0xcd, 0xb9, 0x0d,
	0x52, 0xbf, 0xad, 0x4c, 0x7d, 0xa8, 0xb9, 0xde, 0xd2, 0x9d, 0xcc, 0x4c, 0xe0, 0x2b, 0x98, 0x33,
	0x34, 0xbf, 0x44, 0xa2, 0x9b, 0x90, 0xb4, 0xf5, 0x89, 0x67, 0x53, 0x74, 0x2f, 0x05, 0x13, 0xb9,
	0x6e, 0xd1, 0x33, 0x42, 0xc0, 0x20, 0xa7, 0x44, 0x7e, 0x5a, 0x50, 0x49, 0x57, 0x63, 0x05, 0x6c,
	0x77, 0xdf, 0x29, 0xe0, 0x53, 0x70, 0x18, 0xfd, 0x48, 0x77, 0x3c, 0xba, 0xcb, 0xbd, 0xc6, 0x21,
	0x75, 0xdb, 0x9e, 0x63, 0xe1, 0x22, 0x60, 0x8e, 0x36, 0x5d, 0xbe, 0xdd, 0xde, 0xd9, 0xa7, 0x9e,
	0x63, 0xe3, 0x33, 0x58, 0xba, 0xe9, 0x76, 0x5d, 0x7e, 0xb8, 0xd5, 0xfc, 0x6c, 0xaa, 0x2d, 0xa7,
	0x88, 0xaf, 0x81, 0xfc, 0x5b, 0xf6, 0xdc, 0x7d, 0xda, 0x6c, 0x71, 0x46, 0x8f, 0xda, 0xb4, 0xe5,
	0xd1, 0x5d, 0xa7, 0x84, 0xab, 0x50, 0xcb, 0xfb, 0x1a, 0xcd, 0xe3, 0xad, 0x83, 0xc6, 0x6e, 0x56,
	0x77, 0xca, 0xb8, 0x04, 0x0b, 0x79, 0xb5, 0x45, 0xd9, 0x31, 0x65, 0x9c, 0x32, 0xe6, 0x32, 0xa7,
	0x42, 0x7e, 0x58, 0x30, 0xdb, 0xee, 0x9d, 0x09, 0x25, 0x1f, 0x28, 0x40, 0x08, 0xa5, 0xd8, 0xff,
	0x2a, 0x8d, 0x56, 0xfa, 0x1b, 0x57, 0x60, 0xfa, 0xdc, 0xef, 0x74, 0x78, 0x24, 0x54, 0x16, 0x8d,
	0xa9, 0x04, 0x60, 0x42, 0x49, 0xac, 0xc3, 0x7c, 0x9e, 0x84, 0xb0, 0x9f, 0x6b, 0x5d, 0xd6, 0x6d,
	0x4f, 0x06, 0x26, 0x07, 0x61, 0x3f, 0x93, 0xfc, 0xbb, 0x05, 0x73, 0xd9, 0x89, 0x4d, 0x12, 0x3e,
	0x8c, 0x24, 0xe1, 0xe5, 0x70, 0x12, 0x86, 0xbb, 0x47, 0xa2, 0x40, 0xf8, 0x3d, 0x1d, 0x9c, 0x24,
	0xb1, 0x3d, 0x5e, 0xe2, 0x22, 0x39, 0x80, 0x99, 0x46, 0xf7, 0x3c, 0x7c, 0x18, 0x7d, 0xc9, 0x37,
	0x1b, 0xaa, 0xe9, 0x3a, 0x43, 0xfe, 0xdd, 0x08, 0xf9, 0x17, 0xc3, 0xe4, 0x6f, 0xf7, 0x8e, 0xde,
	0x82, 0xcc, 0x2b, 0x7b, 0x9c, 0x57, 0xc5, 0xfb, 0x79, 0x55, 0x1a, 0xe7, 0xd5, 0xe0, 0x3f, 0x6f,
	0xc7, 0x24, 0xcd, 0x8b, 0xe3, 0x35, 0x2f, 0x6d, 0xfc, 0xb6, 0xa0, 0x7a, 0x94, 0xc8, 0xd0, 0x4a,
	0x65, 0xc0, 0x6d, 0x28, 0xeb, 0x07, 0x01, 0x97, 0xef, 0x7c, 0x25, 0xb4, 0x35, 0xcb, 0x2b, 0x13,
	0x5e, 0x10, 0x52, 0x40, 0x0a, 0x95, 0x34, 0x4a, 0xb8, 0x72, 0x77, 0xc0, 0xd2, 0x2d, 0xab, 0x93,
	0xd2, 0x47, 0x0a, 0xb8, 0x0d, 0x8f, 0xf6, 0xa4, 0x4a, 0x7c, 0xc1, 0xa5, 0xbb, 0xbc, 0x4a, 0xb7,
	0x2c, 0x8f, 0xb7, 0x91, 0x14, 0x4e, 0x2a, 0xfa, 0x5f, 0xb0, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x90, 0xc4, 0x34, 0x3c, 0x22, 0x06, 0x00, 0x00,
}
